.PHONY: run

# set port to default port if port is not specified in command line
ifeq ($(PORT),)
PORT = 8080
endif

build:
		docker build -t my-py-server-image .

run-prod: 
		docker run --rm -it --name py-server --env PORT=$(PORT) -p 7000:$(PORT) my-py-server-image

run-dev:
		python3 server.py --port ${PORT}

bash:
		docker exec -it py-server bash

help:
		@echo 'Usage: make [TARGET] [EXTRA_ARGUMENTS]'
		@echo 'Targets:'
		@echo '  build    	build docker --image--'
		@echo '  run-prod  	runs the python server inside a docker --container-- with the port argument from command line'
		@echo '  run-dev    runs the python server locally, requires python v.3.8 the port argument from command line'
		@echo '  bash   	get inside the docker container which was previously run with make run-prod'